// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API_Asp_Net_Core__Com_Angular.Models;

namespace Web_API_Asp_Net_Core__Com_Angular.Migrations
{
    [DbContext(typeof(ApiDBContext))]
    [Migration("20210214215314_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_API_Asp_Net_Core__Com_Angular.Models.Banco", b =>
                {
                    b.Property<int>("BancoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BancoNome")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BancoId");

                    b.ToTable("Banco");
                });

            modelBuilder.Entity("Web_API_Asp_Net_Core__Com_Angular.Models.BancoConta", b =>
                {
                    b.Property<int>("BancoContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BRFSC")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("BancoId")
                        .HasColumnType("int");

                    b.Property<string>("ContaNumero")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ContaSeguradora")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BancoContaId");

                    b.ToTable("BancoConta");
                });
#pragma warning restore 612, 618
        }
    }
}
